name: e2t1m0t0r_frontend
description: A frontend for the e2t1m0t0r service
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: 3.3.8

dependencies:
  bloc: ^8.1.0
  dio: ^4.0.6
  drag_and_drop_flutter: ^0.3.0
  file_picker: ^5.2.4
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0

dev_dependencies:
  bloc_test: ^9.1.0
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^3.1.0

flutter:
  uses-material-design: true
  generate: true
